In [1]:
"""
Constructs the meshes from the volumetric data and from the 2.5D shapes.
"""

import napari_spatialdata.constants.config
import spatialdata as sd
from pathlib import Path
from numpy.random import default_rng

from tissue_map_tools.igneous_converters import (  # noqa: F401
    from_spatialdata_raster_to_sharded_precomputed_raster_and_meshes,
)
from tissue_map_tools.data_model.annotations_utils import (
    make_dtypes_compatible_with_precomputed_annotations,
)
import time  # noqa: F401
import shutil  # noqa: F401
from tissue_map_tools.converters import (  # noqa: F401
    from_spatialdata_points_to_precomputed_points,
)

RNG = default_rng(42)

/Users/macbook/embl/projects/basel/3d-spatial-workshop-2025/.venv/lib/python3.12/site-packages/xarray_schema/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution

In [2]:
out_path = Path.cwd() / "data"
sdata_zarr_path = out_path / "merfish_mouse_ileum.sdata.zarr"
precomputed_path = out_path / "merfish_mouse_ileum_precomputed"

# load the data
f = Path(sdata_zarr_path)
sdata = sd.read_zarr(f)

In [3]:
print(sd.get_extent(sdata["molecules"]))

{'x': (np.float64(112.0), np.float64(5720.0)), 'y': (np.float64(0.0), np.float64(9391.0)), 'z': (np.float64(0.0), np.float64(110.1455251))}

In [4]:
##
# subset the data
sdata_small = sd.bounding_box_query(
    sdata,
    axes=("x", "y", "z"),
    min_coordinate=[4000, 0, -10],
    max_coordinate=[5000, 1500, 200],
    target_coordinate_system="global",
)

/Users/macbook/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: UserWarning: The object has `points` element. Depending on the number of points, querying MAY suffer from performance issues. Please consider filtering the object before calling this function by calling the `subset()` method of `SpatialData`.
  return dispatch(args[0].__class__)(*args, **kw)

In [5]:
# we need to transform the vector data to match the image due to this issue:
# https://github.com/hms-dbmi/tissue-map-tools/issues/13
transformation = sd.transformations.get_transformation(sdata_small["stains"])
translation_vector = transformation.to_affine_matrix(
    input_axes=("x", "y", "z"), output_axes=("x", "y", "z")
)[:3, 3]
translation = sd.transformations.Translation(translation_vector, axes=("x", "y", "z"))
for _, element_name, _ in sdata_small.gen_spatial_elements():
    old_transformation = sd.transformations.get_transformation(
        sdata_small[element_name]
    )
    sequence = sd.transformations.Sequence([old_transformation, translation.inverse()])
    sd.transformations.set_transformation(
        sdata_small[element_name],
        transformation=sequence,
        to_coordinate_system="global",
    )
    if sd.models.get_model(sdata_small[element_name]) not in (
        sd.models.Image3DModel,
        sd.models.Labels3DModel,
    ):
        transformed = sd.transform(sdata_small[element_name], to_coordinate_system="global")
        sdata_small[element_name] = transformed

sdata = sdata_small

In [6]:
##
#
# cells_baysor_cropped = sd.bounding_box_query(
#     sdata["cells_baysor"],
#     axes=("x", "y", "z"),
#     min_coordinate=[1500, 1500, -10],
#     max_coordinate=[3000, 3000, 200],
#     target_coordinate_system="global",
# )
# sdata["cells_baysor"] = cells_baysor_cropped

##
from_spatialdata_raster_to_sharded_precomputed_raster_and_meshes(
    raster=sdata["dapi_labels"],
    precomputed_path=str(precomputed_path),
)

##
# from_spatialdata_raster_to_sharded_precomputed_raster_and_meshes(
#     raster=sdata["membrane_labels"],
#     precomputed_path=str(precomputed_path),
# )


##

Converted OME-Zarr data to the Precomputed format (segmentation) at /Users/macbook/embl/projects/basel/3d-spatial-workshop-2025/data/merfish_mouse_ileum_precomputed with pixel sizes {'x': 1000, 'y': 1000, 'z': 13768} and axes ['x', 'y', 'z'].
Volume Bounds:  Bbox([0, 0, 0],[1000, 1500, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[1000, 1500, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.06it/s]

Volume Bounds:  Bbox([0, 0, 0],[500, 750, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[500, 750, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.15it/s]

Volume Bounds:  Bbox([0, 0, 0],[250, 375, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[250, 375, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 36.92it/s]

Volume Bounds:  Bbox([0, 0, 0],[125, 188, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[125, 188, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 66.11it/s]
Tasks:   0%|                                                                                                              | 0/12 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/24 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/16 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                         | 0/6 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/16 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/16 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 673.52it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 530.68it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1784.48it/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 222.49it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 606.50it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1878.43it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 750.26it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2219.76it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2278.62it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 1319.26it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2436.14it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2569.25it/s]
Tasks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  5.46it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 105.98it/s]
Decoding Labels: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 7182.03it/s]
Tasks:   0%|                                                                                                               | 0/1 [00:00<?, ?it/s]
Processing Index:   0%|                                                                                                   | 0/12 [00:00<?, ?it/s]
Processing Index: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 50.61it/s]
Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.84it/s]

In [7]:
subset = RNG.choice(len(sdata["molecule_baysor"]), 10000, replace=False)

print(sdata["molecule_baysor"].columns)
subset_df = sdata["molecule_baysor"].compute().iloc[subset]
# subset_df = sdata["molecule_baysor"].compute()
subset_df = subset_df[
    [
        # working
        "x",
        "y",
        "z",
        "gene",
        "area",
        "mol_id",
        "x_raw",
        "y_raw",
        "z_raw",
        "brightness",
        "total_magnitude",
        "compartment",
        "nuclei_probs",
        "assignment_confidence",
        #
        "cell",
        "is_noise",  # TODO: bool not working at the moment
        # "ncv_color",  # TODO: represent as RGB
        "layer",
    ]
]
subset_df

Index(['mol_id', 'x_raw', 'y_raw', 'z_raw', 'gene', 'area', 'brightness',
       'total_magnitude', 'qc_score', 'molecule_id', 'confidence',
       'compartment', 'nuclei_probs', 'cell', 'assignment_confidence',
       'is_noise', 'ncv_color', 'layer', 'x', 'y', 'z'],
      dtype='object')

,x,y,z,gene,area,mol_id,x_raw,y_raw,z_raw,brightness,total_magnitude,compartment,nuclei_probs,assignment_confidence,cell,is_noise,layer
460642,500.0,841.0,2.753638e+01,Lpar1,15,10095018,-2630.866,-1265.363,5.5,1.875414,1125.9140,Cyto,0.025976,0.675,867,False,3
423082,952.0,761.0,5.507276e+01,Clca3b,6,10003055,-2581.609,-1274.128,8.5,2.150356,848.2183,Unknown,0.986717,1.000,1045,False,5
413076,84.0,444.0,-2.945800e-09,Txndc5,4,9988714,-2676.138,-1308.672,2.5,2.008227,407.6496,Unknown,0.967683,1.000,511,False,1
444843,715.0,1069.0,4.130457e+01,Gp2,3,10048842,-2607.459,-1240.554,7.0,2.013750,309.6504,Unknown,0.940632,0.825,1085,False,4
451885,292.0,1144.0,-2.945800e-09,Sdc1,4,10069068,-2653.550,-1232.399,2.5,2.038763,437.3442,Unknown,0.818268,0.825,0,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426314,356.0,1094.0,-2.945800e-09,Adgrf5,15,10011807,-2646.565,-1237.818,2.5,2.164938,2192.9530,Unknown,1.000000,0.875,5284,False,1
426622,862.0,827.0,6.884095e+01,Adgrf5,5,10012460,-2591.478,-1266.878,10.0,1.544077,175.0038,Cyto,0.019236,0.275,5702,False,6
442791,867.0,800.0,4.130457e+01,Nlrp6,4,10044869,-2590.909,-1269.846,7.0,1.915653,329.3920,Cyto,0.091038,0.950,1022,False,4
450905,183.0,1297.0,2.753638e+01,Mzb1,4,10067050,-2665.387,-1215.732,5.5,1.781510,241.8634,Unknown,1.000000,1.000,905,False,3
403277,355.0,296.0,4.130457e+01,Slc51a,3,9973139,-2646.660,-1324.747,7.0,1.815285,196.0677,Unknown,0.972362,0.950,526,False,4

In [8]:
make_dtypes_compatible_with_precomputed_annotations(
    subset_df,
    max_categories=250,
    check_for_overflow=True,
)

,x,y,z,gene,area,mol_id,x_raw,y_raw,z_raw,brightness,total_magnitude,compartment,nuclei_probs,assignment_confidence,cell,is_noise,layer
460642,500.0,841.0,2.753638e+01,Lpar1,15,10095018,-2630.865967,-1265.363037,5.5,1.875414,1125.913940,Cyto,0.025976,0.675,867,0,3
423082,952.0,761.0,5.507276e+01,Clca3b,6,10003055,-2581.608887,-1274.128052,8.5,2.150356,848.218323,Unknown,0.986717,1.000,1045,0,5
413076,84.0,444.0,-2.945800e-09,Txndc5,4,9988714,-2676.137939,-1308.671997,2.5,2.008227,407.649597,Unknown,0.967683,1.000,511,0,1
444843,715.0,1069.0,4.130457e+01,Gp2,3,10048842,-2607.458984,-1240.553955,7.0,2.013750,309.650391,Unknown,0.940632,0.825,1085,0,4
451885,292.0,1144.0,-2.945800e-09,Sdc1,4,10069068,-2653.550049,-1232.399048,2.5,2.038763,437.344208,Unknown,0.818268,0.825,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426314,356.0,1094.0,-2.945800e-09,Adgrf5,15,10011807,-2646.564941,-1237.817993,2.5,2.164938,2192.952881,Unknown,1.000000,0.875,5284,0,1
426622,862.0,827.0,6.884095e+01,Adgrf5,5,10012460,-2591.478027,-1266.878052,10.0,1.544078,175.003799,Cyto,0.019236,0.275,5702,0,6
442791,867.0,800.0,4.130457e+01,Nlrp6,4,10044869,-2590.908936,-1269.845947,7.0,1.915653,329.391998,Cyto,0.091038,0.950,1022,0,4
450905,183.0,1297.0,2.753638e+01,Mzb1,4,10067050,-2665.386963,-1215.732056,5.5,1.781510,241.863403,Unknown,1.000000,1.000,905,0,3
403277,355.0,296.0,4.130457e+01,Slc51a,3,9973139,-2646.659912,-1324.746948,7.0,1.815285,196.067703,Unknown,0.972362,0.950,526,0,4

In [9]:
sdata["molecule_baysor"] = sd.models.PointsModel.parse(subset_df)

# TODO: temporary workaround: raster data converted to precomputed expresses units in nm
#  therefore let's multiply the points by 1000
for ax in ["x", "y", "z"]:
    sdata["molecule_baysor"][ax] = sdata["molecule_baysor"][ax] * 1000


##
# debug
points = sdata["molecule_baysor"].compute().iloc[:2]
print("point 0")
print(points.iloc[0])
print("")
print("point 1")
print(points.iloc[1])
print("")
print(points.x.dtype)
# print(points.gene.cat.categories)
print(points.gene.cat.categories.get_loc(points.gene.iloc[0]))
##
print("converting the points to the precomputed format")

# TODO: there should be no need to add the subpath (we should be able to specify the
#  parent cloud volume object
# TODO: the info file in the parent volume should be updated to include the points
# TODO: the view APIs show include the points

start = time.time()
path = precomputed_path / "molecule_baysor"
if path.exists():
    shutil.rmtree(path)

/Users/macbook/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:946: UserWarning: The index of the dataframe is not monotonic increasing. It is recommended to sort the data to adjust the order of the index before calling .parse() (or call `parse(sort=True)`) to avoid possible problems due to unknown divisions.
  return method.__get__(obj, cls)(*args, **kwargs)

point 0
x                            500000.0
y                            841000.0
z                        27536.380859
gene                            Lpar1
area                               15
mol_id                       10095018
x_raw                    -2630.865967
y_raw                    -1265.363037
z_raw                             5.5
brightness                   1.875414
total_magnitude            1125.91394
compartment                      Cyto
nuclei_probs                 0.025976
assignment_confidence           0.675
cell                              867
is_noise                            0
layer                               3
Name: 460642, dtype: object

point 1
x                            952000.0
y                            761000.0
z                        55072.761719
gene                           Clca3b
area                                6
mol_id                       10003055
x_raw                    -2581.608887
y_raw                    -1274.128052
z_raw                             8.5
brightness                   2.150356
total_magnitude            848.218323
compartment                   Unknown
nuclei_probs                 0.986717
assignment_confidence             1.0
cell                             1045
is_noise                            0
layer                               5
Name: 423082, dtype: object

float32
140
converting the points to the precomputed format

In [10]:
from_spatialdata_points_to_precomputed_points(
    sdata["molecule_baysor"],
    precomputed_path=precomputed_path,
    points_name="molecule_baysor",
    limit=1000,
    # limit=500,
)
print(f"conversion of points: {time.time() - start}")

Processing grid level 0 with shape (1, 1, 1) and chunk size [ 998000.        1498000.         110145.5234375]. Remaining points: 10000
Emitting 1000 points for grid cell (0, 0, 0)
Processing grid level 1 with shape (2, 2, 1) and chunk size [499000.        749000.        110145.5234375]. Remaining points: 9000
Emitting 1000 points for grid cell (0, 0, 0)
Emitting 1000 points for grid cell (0, 1, 0)
Emitting 1000 points for grid cell (1, 0, 0)
Emitting 1000 points for grid cell (1, 1, 0)
Processing grid level 2 with shape (4, 4, 1) and chunk size [249500.        374500.        110145.5234375]. Remaining points: 5000
Emitting 438 points for grid cell (0, 0, 0)
Emitting 502 points for grid cell (0, 1, 0)
Emitting 178 points for grid cell (1, 0, 0)
Emitting 239 points for grid cell (1, 1, 0)
Emitting 530 points for grid cell (0, 2, 0)
Emitting 357 points for grid cell (0, 3, 0)
Emitting 318 points for grid cell (1, 2, 0)
Emitting 263 points for grid cell (1, 3, 0)
Emitting 265 points for grid cell (2, 0, 0)
Emitting 422 points for grid cell (2, 1, 0)
Emitting 172 points for grid cell (3, 0, 0)
Emitting 340 points for grid cell (3, 1, 0)
Emitting 318 points for grid cell (2, 2, 0)
Emitting 249 points for grid cell (2, 3, 0)
Emitting 249 points for grid cell (3, 2, 0)
Emitting 160 points for grid cell (3, 3, 0)
{
    "type": "neuroglancer_annotations_v1",
    "dimensions": {
        "x": [
            1.0,
            "nm"
        ],
        "y": [
            1.0,
            "nm"
        ],
        "z": [
            1.0,
            "nm"
        ]
    },
    "lower_bound": [
        1000.0,
        1000.0,
        -2.945800133602461e-6
    ],
    "upper_bound": [
        999000.0,
        1499000.0,
        110145.5234375
    ],
    "annotation_type": "POINT",
    "properties": [
        {
            "id": "gene",
            "type": "int16",
            "description": "",
            "enum_values": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                87,
                88,
                89,
                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                99,
                100,
                101,
                102,
                103,
                104,
                105,
                106,
                107,
                108,
                109,
                110,
                111,
                112,
                113,
                114,
                115,
                116,
                117,
                118,
                119,
                120,
                121,
                122,
                123,
                124,
                125,
                126,
                127,
                128,
                129,
                130,
                131,
                132,
                133,
                134,
                135,
                136,
                137,
                138,
                139,
                140,
                141,
                142,
                143,
                144,
                145,
                146,
                147,
                148,
                149,
                150,
                151,
                152,
                153,
                154,
                155,
                156,
                157,
                158,
                159,
                160,
                161,
                162,
                163,
                164,
                165,
                166,
                167,
                168,
                169,
                170,
                171,
                172,
                173,
                174,
                175,
                176,
                177,
                178,
                179,
                180,
                181,
                182,
                183,
                184,
                185,
                186,
                187,
                188,
                189,
                190,
                191,
                192,
                193,
                194,
                195,
                196,
                197,
                198,
                199,
                200,
                201,
                202,
                203,
                204,
                205,
                206,
                207,
                208,
                209,
                210,
                211,
                212,
                213,
                214,
                215,
                216,
                217,
                218,
                219,
                220,
                221,
                222,
                223,
                224,
                225,
                226,
                227,
                228,
                229,
                230,
                231,
                232,
                233,
                234,
                235,
                236,
                237,
                238,
                239,
                240
            ],
            "enum_labels": [
                "Acsl1",
                "Acta2",
                "Ada",
                "Adgrd1",
                "Adgrf5",
                "Adra1a",
                "Adra1b",
                "Adra1d",
                "Adra2a",
                "Adra2b",
                "Adra2c",
                "Adrb1",
                "Adrb2",
                "Adrb3",
                "Agr3",
                "Apob",
                "Avil",
                "C1qb",
                "C1qc",
                "Cadm1",
                "Cckar",
                "Cckbr",
                "Ccl9",
                "Ccnl2",
                "Ccr3",
                "Ccr7",
                "Cd14",
                "Cd27",
                "Cd34",
                "Cd3d",
                "Cd3e",
                "Cd4",
                "Cd44",
                "Cd79a",
                "Cd79b",
                "Cd8a",
                "Cd8b1",
                "Chrm1",
                "Chrm2",
                "Chrm3",
                "Chrm4",
                "Chrm5",
                "Clca3b",
                "Clec4a2",
                "Clec9a",
                "Cmc1",
                "Cnr1",
                "Cps1",
                "Crp",
                "Cspg4",
                "Cxcr5",
                "Cysltr1",
                "Cysltr2",
                "Drd1",
                "Drd2",
                "Drd3",
                "Drd4",
                "Drd5",
                "Elavl3",
                "Etv1",
                "Fcer1a",
                "Fcgr4",
                "Fcna",
                "Ffar1",
                "Ffar2",
                "Ffar3",
                "Ffar4",
                "Foxp3",
                "Fzd1",
                "Fzd10",
                "Fzd2",
                "Fzd3",
                "Fzd4",
                "Fzd5",
                "Fzd6",
                "Fzd7",
                "Fzd8",
                "Fzd9",
                "Galr1",
                "Galr2",
                "Galr3",
                "Gcgr",
                "Ghsr",
                "Gipr",
                "Glp1r",
                "Glp2r",
                "Gp2",
                "Gpbar1",
                "Gper1",
                "Gpr119",
                "Gpr174",
                "Gpr18",
                "Gpr31b",
                "Gpr34",
                "Gpr55",
                "Gpr84",
                "Gpr87",
                "Gzmb",
                "H2-Eb1",
                "Hhex",
                "Hmgb2",
                "Hrh1",
                "Hrh2",
                "Hrh3",
                "Hrh4",
                "Htr1a",
                "Htr1b",
                "Htr1d",
                "Htr1f",
                "Htr2a",
                "Htr2b",
                "Htr2c",
                "Htr4",
                "Htr5a",
                "Htr5b",
                "Htr6",
                "Htr7",
                "Icos",
                "Ifnar1",
                "Ifng",
                "Ighd",
                "Il10",
                "Il17a",
                "Il3ra",
                "Il4",
                "Il5",
                "Il7r",
                "Il9",
                "Isl1",
                "Itgae",
                "Itgam",
                "Jaml",
                "Kiss1r",
                "Kit",
                "Klk1",
                "Krt7",
                "Lamp3",
                "Lct",
                "Lgr5",
                "Lmx1a",
                "Lpar1",
                "Lpar2",
                "Lpar3",
                "Lpar4",
                "Lpar5",
                "Lpar6",
                "Lrmp",
                "Ltb4r1",
                "Ltb4r2",
                "Ly6g",
                "Maged2",
                "Maoa",
                "Marcksl1",
                "Mboat4",
                "Mki67",
                "Mpo",
                "Mptx2",
                "Ms4a1",
                "Mzb1",
                "Neat1",
                "Nes",
                "Net1",
                "Neurog3",
                "Nkg7",
                "Nlrp6",
                "Nt5e",
                "Ntsr1",
                "Ntsr2",
                "P2ry10",
                "P2ry10b",
                "Pax6",
                "Phox2b",
                "Plb1",
                "Prf1",
                "Ptgdr",
                "Ptgdr2",
                "Ptger1",
                "Ptger2",
                "Ptger3",
                "Ptger4",
                "Ptgfr",
                "Ptgir",
                "Ptprcap",
                "Pzp",
                "Rcor2",
                "Rgs4",
                "S100b",
                "S1pr1",
                "S1pr2",
                "S1pr3",
                "S1pr4",
                "S1pr5",
                "Scarb1",
                "Scn3a",
                "Sctr",
                "Sdc1",
                "Sell",
                "Slc12a2",
                "Slc18a1",
                "Slc26a4",
                "Slc2a2",
                "Slc51a",
                "Slc5a1",
                "Smo",
                "Sox10",
                "Sox4",
                "Sstr1",
                "Sstr2",
                "Sstr3",
                "Sstr4",
                "Sstr5",
                "Stmn1",
                "Taar1",
                "Taar2",
                "Taar3",
                "Taar4",
                "Taar5",
                "Taar6",
                "Taar7a",
                "Taar7b",
                "Taar7d",
                "Taar7e",
                "Taar7f",
                "Taar8a",
                "Taar8b",
                "Taar8c",
                "Taar9",
                "Tbx21",
                "Tbxa2r",
                "Thy1",
                "Tigit",
                "Tm4sf4",
                "Tnfrsf21",
                "Tpsb2",
                "Trdc",
                "Trpm5",
                "Tspan13",
                "Txndc5",
                "Tymp",
                "Vcan",
                "Vim"
            ]
        },
        {
            "id": "area",
            "type": "int32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "mol_id",
            "type": "int32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "x_raw",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "y_raw",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "z_raw",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "brightness",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "total_magnitude",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "compartment",
            "type": "int8",
            "description": "",
            "enum_values": [
                0,
                1,
                2
            ],
            "enum_labels": [
                "Cyto",
                "Nuclei",
                "Unknown"
            ]
        },
        {
            "id": "nuclei_probs",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "assignment_confidence",
            "type": "float32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "cell",
            "type": "int32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "is_noise",
            "type": "int8",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        },
        {
            "id": "layer",
            "type": "int32",
            "description": "",
            "enum_values": null,
            "enum_labels": null
        }
    ],
    "relationships": [
        {
            "id": "neighbors_a",
            "key": "neighbors_a",
            "sharding": null
        },
        {
            "id": "neighbors_b",
            "key": "neighbors_b",
            "sharding": null
        },
        {
            "id": "neighbors_c",
            "key": "neighbors_c",
            "sharding": null
        }
    ],
    "by_id": {
        "key": "by_id",
        "sharding": null
    },
    "spatial": [
        {
            "key": "spatial0",
            "sharding": null,
            "grid_shape": [
                1,
                1,
                1
            ],
            "chunk_size": [
                998000.0,
                1498000.0,
                110145.5234375
            ],
            "limit": 1000
        },
        {
            "key": "spatial1",
            "sharding": null,
            "grid_shape": [
                2,
                2,
                1
            ],
            "chunk_size": [
                499000.0,
                749000.0,
                110145.5234375
            ],
            "limit": 1000
        },
        {
            "key": "spatial2",
            "sharding": null,
            "grid_shape": [
                4,
                4,
                1
            ],
            "chunk_size": [
                249500.0,
                374500.0,
                110145.5234375
            ],
            "limit": 1000
        }
    ]
}
conversion of points: 8.69161605834961

In [11]:
print('done')

done