In [1]:
"""
Constructs the meshes from the volumetric data and from the 2.5D shapes.
"""

import napari_spatialdata.constants.config
import spatialdata as sd
from pathlib import Path
from numpy.random import default_rng

from tissue_map_tools.igneous_converters import (  # noqa: F401
    from_spatialdata_raster_to_sharded_precomputed_raster_and_meshes,
)
from tissue_map_tools.data_model.annotations_utils import (
    make_dtypes_compatible_with_precomputed_annotations,
)
import time  # noqa: F401
import shutil  # noqa: F401
from tissue_map_tools.converters import (  # noqa: F401
    from_spatialdata_points_to_precomputed_points,
)
from tissue_map_tools.data_model.annotations_utils import parse_annotations

RNG = default_rng(42)

SMALL_DATA = True

/Users/macbook/embl/projects/basel/3d-spatial-workshop-2025/.venv/lib/python3.12/site-packages/xarray_schema/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution

In [2]:
out_path = Path.cwd() / "data"
sdata_zarr_path = out_path / "merfish_mouse_ileum.sdata.zarr"
precomputed_path = out_path / "merfish_mouse_ileum_precomputed" + ('' if SMALL_DATA else '_full')

# load the data
f = Path(sdata_zarr_path)
sdata = sd.read_zarr(f)

In [3]:
print(sd.get_extent(sdata["molecules"]))

{'x': (np.float64(112.0), np.float64(5720.0)), 'y': (np.float64(0.0), np.float64(9391.0)), 'z': (np.float64(0.0), np.float64(110.1455251))}

Let's subset the data in order to run this example notebook faster. Setting `SMALL_SDATA = False` will use the full data.

In [4]:
##
# subset the data
sdata_small = sd.bounding_box_query(
    sdata,
    axes=("x", "y", "z"),
    min_coordinate=[4000, 0, -10],
    max_coordinate=[5000, 1500, 200],
    target_coordinate_system="global",
)

/Users/macbook/.local/share/uv/python/cpython-3.12.8-macos-aarch64-none/lib/python3.12/functools.py:909: UserWarning: The object has `points` element. Depending on the number of points, querying MAY suffer from performance issues. Please consider filtering the object before calling this function by calling the `subset()` method of `SpatialData`.
  return dispatch(args[0].__class__)(*args, **kw)

In [5]:
# we need to transform the vector data to match the image due to this issue:
# https://github.com/hms-dbmi/tissue-map-tools/issues/13
transformation = sd.transformations.get_transformation(sdata_small["stains"])
translation_vector = transformation.to_affine_matrix(
    input_axes=("x", "y", "z"), output_axes=("x", "y", "z")
)[:3, 3]
translation = sd.transformations.Translation(translation_vector, axes=("x", "y", "z"))
for _, element_name, _ in sdata_small.gen_spatial_elements():
    old_transformation = sd.transformations.get_transformation(
        sdata_small[element_name]
    )
    sequence = sd.transformations.Sequence([old_transformation, translation.inverse()])
    sd.transformations.set_transformation(
        sdata_small[element_name],
        transformation=sequence,
        to_coordinate_system="global",
    )
    if sd.models.get_model(sdata_small[element_name]) not in (
        sd.models.Image3DModel,
        sd.models.Labels3DModel,
    ):
        transformed = sd.transform(sdata_small[element_name], to_coordinate_system="global")
        sdata_small[element_name] = transformed

if SMALL_DATA:
    sdata = sdata_small

Let's convert the `SpatialData` Zarr storage to the [Neuroglancer Precomputed format](https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/annotations.md), to enable visualization with `neuroglancer`.

In [6]:
from_spatialdata_raster_to_sharded_precomputed_raster_and_meshes(
    raster=sdata["dapi_labels"],
    precomputed_path=str(precomputed_path),
)

Converted OME-Zarr data to the Precomputed format (segmentation) at _full with pixel sizes {'x': 1000, 'y': 1000, 'z': 13768} and axes ['x', 'y', 'z'].
Volume Bounds:  Bbox([0, 0, 0],[5721, 9392, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[5721, 9392, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.78s/it]

Volume Bounds:  Bbox([0, 0, 0],[2861, 4696, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[2861, 4696, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.57s/it]

Volume Bounds:  Bbox([0, 0, 0],[1431, 2348, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[1431, 2348, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.05it/s]

Volume Bounds:  Bbox([0, 0, 0],[716, 1174, 9], dtype=np.int32, unit='vx')
Selected ROI:   Bbox([0, 0, 0],[716, 1174, 9], dtype=np.int32, unit='vx')

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.93it/s]
Tasks:   0%|                                                                                                             | 0/273 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/48 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 1058.48it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1246.11it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1399.49it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1447.05it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1863.50it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1443.00it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1502.91it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1685.01it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1788.06it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1849.33it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1933.58it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2003.56it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2159.16it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2173.41it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1197.18it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1299.34it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1347.80it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2447.53it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1322.78it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1100.26it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1005.48it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2362.51it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3458.55it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3582.05it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3226.81it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 3586.66it/s]

Tasks:   3%|██▌                                                                                                  | 7/273 [00:02<01:28,  3.01it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2769.23it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3818.16it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3845.45it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3323.45it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3527.54it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3247.58it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2867.13it/s]
Tasks:   3%|██▉                                                                                                  | 8/273 [00:02<01:38,  2.68it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2451.67it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3917.79it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3498.21it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3250.57it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3740.27it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 3432.74it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1925.15it/s]
Tasks:   4%|███▋                                                                                                | 10/273 [00:03<01:50,  2.38it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3254.39it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2807.29it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3011.09it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3562.66it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3435.18it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2010.57it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 309.81it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3631.63it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 4384.41it/s]
Tasks:   9%|████████▊                                                                                           | 24/273 [00:04<00:29,  8.42it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 4277.72it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3715.52it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 4409.74it/s]
Tasks:  12%|████████████                                                                                        | 33/273 [00:05<00:23, 10.42it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3278.20it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1311.02it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2337.29it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3821.80it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3911.29it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3748.42it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2166.04it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3640.30it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3395.94it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3427.81it/s]
Tasks:  13%|████████████▊                                                                                       | 35/273 [00:06<00:38,  6.23it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3360.86it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3307.32it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 3435.49it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2506.00it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2445.37it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2645.94it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3220.77it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3301.34it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3577.61it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3782.01it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 1279.13it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3986.74it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2713.96it/s]

Tasks:  18%|█████████████████▌                                                                                  | 48/273 [00:07<00:35,  6.40it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2757.31it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3402.22it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 3773.27it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3636.35it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3957.24it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3378.03it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3009.37it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3305.81it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2838.99it/s]

Tasks:  22%|█████████████████████▌                                                                              | 59/273 [00:08<00:25,  8.27it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 722.23it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2361.99it/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3214.14it/s]

Downloading:   0%|                                                                                                        | 0/64 [00:00<?, ?it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3589.48it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 3483.78it/s]
Tasks:  22%|██████████████████████▎                                                                             | 61/273 [00:09<00:29,  7.17it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 2757.20it/s]

Downloading:   0%|                                                                                                        | 0/48 [00:00<?, ?it/s]

We also create the meshes in the unsharded format (later we will use them in Vitessce, who only support the unsharded format so far).

In [8]:
from tissue_map_tools.igneous_converters import from_precomputed_raster_to_precomputed_meshes

from_precomputed_raster_to_precomputed_meshes(
    data_path=str(precomputed_path),
    mesh_name='mesh_mip_0_err_40_unsharded',
    sharded=False,
)

Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 273/273 [00:33<00:00,  8.11it/s]
Tasks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 999/999 [00:19<00:00, 51.41it/s]

Here we choose if subsetting the points data or we keep the full dataset, and we choose which features to keep.

In [9]:
subset = RNG.choice(len(sdata["molecule_baysor"]), 10000, replace=False)

print(sdata["molecule_baysor"].columns)
if SMALL_DATA:
    subset_df = sdata["molecule_baysor"].compute().iloc[subset]
else:
    subset_df = sdata["molecule_baysor"].compute()
subset_df = subset_df[
    [
        "x",
        "y",
        "z",
        "gene",
        "area",
        "mol_id",
        "x_raw",
        "y_raw",
        "z_raw",
        "brightness",
        "total_magnitude",
        "compartment",
        "nuclei_probs",
        "assignment_confidence",
        "cell",
        "is_noise",
        "layer",
    ]
]
subset_df

Index(['mol_id', 'x_raw', 'y_raw', 'z_raw', 'gene', 'area', 'brightness',
       'total_magnitude', 'qc_score', 'x', 'y', 'z', 'molecule_id',
       'confidence', 'compartment', 'nuclei_probs', 'cell',
       'assignment_confidence', 'is_noise', 'ncv_color', 'layer'],
      dtype='object')

,x,y,z,gene,area,mol_id,x_raw,y_raw,z_raw,brightness,total_magnitude,compartment,nuclei_probs,assignment_confidence,cell,is_noise,layer
0,1705.0,1271.0,0.000000,Maoa,4,3048145,-2935.386,-1218.580,2.5,2.021306,420.1126,Unknown,1.000000,0.625,75,False,1
1,1725.0,1922.0,0.000000,Maoa,4,3048147,-2933.229,-1147.614,2.5,1.828640,269.5874,Unknown,1.000000,0.950,189,False,1
2,1753.0,1863.0,0.000000,Maoa,5,3048148,-2930.104,-1154.062,2.5,2.001268,501.4615,Unknown,1.000000,1.000,188,False,1
3,1760.0,1865.0,0.000000,Maoa,7,3048149,-2929.339,-1153.784,2.5,1.960428,639.0364,Unknown,1.000000,1.000,188,False,1
4,1904.0,794.0,0.000000,Maoa,6,3048153,-2913.718,-1270.474,2.5,1.937280,519.3154,Unknown,1.000000,0.575,0,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819660,5704.0,38.0,13.768191,Hrh1,3,17236830,-2499.651,-1352.890,4.0,1.823321,199.7294,Cyto,0.533283,0.700,1020,False,2
819661,5685.0,43.0,13.768191,Htr4,3,17238042,-2501.752,-1352.326,4.0,1.833191,204.3206,Cyto,0.580681,0.650,1020,False,2
819662,5631.0,61.0,55.072763,Taar6,4,17239179,-2507.674,-1350.402,8.5,1.662809,184.0217,Unknown,0.668193,1.000,1002,False,5
819663,5720.0,62.0,0.000000,Taar7a,6,17239416,-2497.931,-1350.247,2.5,1.740916,330.4210,Cyto,0.657800,0.900,0,True,1
819664,5635.0,28.0,27.536381,Taar7a,11,17239460,-2507.189,-1353.985,5.5,1.529714,372.4828,Unknown,0.666667,1.000,0,True,3

Ensure that the dtypes are compatible with the `neuroglancer` format. This will be made automatic in `tissue-map-tools`.

In [10]:
make_dtypes_compatible_with_precomputed_annotations(
    subset_df,
    max_categories=250,
    check_for_overflow=True,
)

,x,y,z,gene,area,mol_id,x_raw,y_raw,z_raw,brightness,total_magnitude,compartment,nuclei_probs,assignment_confidence,cell,is_noise,layer
0,1705.0,1271.0,0.000000,Maoa,4,3048145,-2935.385986,-1218.579956,2.5,2.021306,420.112610,Unknown,1.000000,0.625,75,0,1
1,1725.0,1922.0,0.000000,Maoa,4,3048147,-2933.229004,-1147.614014,2.5,1.828640,269.587402,Unknown,1.000000,0.950,189,0,1
2,1753.0,1863.0,0.000000,Maoa,5,3048148,-2930.104004,-1154.062012,2.5,2.001268,501.461487,Unknown,1.000000,1.000,188,0,1
3,1760.0,1865.0,0.000000,Maoa,7,3048149,-2929.339111,-1153.784058,2.5,1.960428,639.036377,Unknown,1.000000,1.000,188,0,1
4,1904.0,794.0,0.000000,Maoa,6,3048153,-2913.718018,-1270.473999,2.5,1.937280,519.315430,Unknown,1.000000,0.575,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819660,5704.0,38.0,13.768190,Hrh1,3,17236830,-2499.650879,-1352.890015,4.0,1.823321,199.729401,Cyto,0.533283,0.700,1020,0,2
819661,5685.0,43.0,13.768190,Htr4,3,17238042,-2501.751953,-1352.326050,4.0,1.833191,204.320602,Cyto,0.580681,0.650,1020,0,2
819662,5631.0,61.0,55.072762,Taar6,4,17239179,-2507.674072,-1350.401978,8.5,1.662809,184.021698,Unknown,0.668193,1.000,1002,0,5
819663,5720.0,62.0,0.000000,Taar7a,6,17239416,-2497.930908,-1350.246948,2.5,1.740916,330.420990,Cyto,0.657800,0.900,0,1,1
819664,5635.0,28.0,27.536381,Taar7a,11,17239460,-2507.188965,-1353.984985,5.5,1.529714,372.482788,Unknown,0.666667,1.000,0,1,3

In [12]:
sdata["molecule_baysor"] = sd.models.PointsModel.parse(subset_df)

# raster data converted to precomputed expresses units in nm therefore let's multiply the points by 1000
# this will be made more ergonomic as part of the tissue-map-tools APIs
for ax in ["x", "y", "z"]:
    sdata["molecule_baysor"][ax] = sdata["molecule_baysor"][ax] * 1000

print("converting the points to the precomputed format")

start = time.time()
path = Path(precomputed_path) / "molecule_baysor"
if path.exists():
    shutil.rmtree(path)

converting the points to the precomputed format

In [13]:
from_spatialdata_points_to_precomputed_points(
    sdata["molecule_baysor"],
    precomputed_path=precomputed_path,
    points_name="molecule_baysor",
    limit=10000,
)
print(f"conversion of points: {time.time() - start}")

Processing grid level 0 with shape (1, 1, 1) and chunk size [5608000.        9391000.         110145.5234375]. Remaining points: 819665
Emitting 10000 points for grid cell (0, 0, 0)
Processing grid level 1 with shape (2, 2, 1) and chunk size [2804000.        4695500.         110145.5234375]. Remaining points: 809665
Emitting 10000 points for grid cell (0, 0, 0)
Emitting 10000 points for grid cell (0, 1, 0)
Emitting 10000 points for grid cell (1, 0, 0)
Emitting 10000 points for grid cell (1, 1, 0)
Processing grid level 2 with shape (4, 4, 1) and chunk size [1402000.        2347750.         110145.5234375]. Remaining points: 769665
Emitting 9220 points for grid cell (0, 0, 0)
Emitting 10000 points for grid cell (0, 1, 0)
Emitting 10000 points for grid cell (1, 0, 0)
Emitting 10000 points for grid cell (1, 1, 0)
Emitting 10000 points for grid cell (0, 2, 0)
Emitting 10000 points for grid cell (0, 3, 0)
Emitting 10000 points for grid cell (1, 2, 0)
Emitting 10000 points for grid cell (1, 3, 0)
Emitting 10000 points for grid cell (2, 0, 0)
Emitting 10000 points for grid cell (2, 1, 0)
Emitting 10000 points for grid cell (3, 0, 0)
Emitting 10000 points for grid cell (3, 1, 0)
Emitting 10000 points for grid cell (2, 2, 0)
Emitting 10000 points for grid cell (2, 3, 0)
Emitting 10000 points for grid cell (3, 2, 0)
Emitting 10000 points for grid cell (3, 3, 0)
Processing grid level 3 with shape (8, 8, 1) and chunk size [ 701000.        1173875.         110145.5234375]. Remaining points: 610445
Emitting 2766 points for grid cell (1, 2, 0)
Emitting 3778 points for grid cell (1, 3, 0)
Emitting 4057 points for grid cell (2, 0, 0)
Emitting 2554 points for grid cell (2, 1, 0)
Emitting 7845 points for grid cell (3, 0, 0)
Emitting 10000 points for grid cell (3, 1, 0)
Emitting 6260 points for grid cell (2, 2, 0)
Emitting 7637 points for grid cell (2, 3, 0)
Emitting 10000 points for grid cell (3, 2, 0)
Emitting 10000 points for grid cell (3, 3, 0)
Emitting 1002 points for grid cell (0, 4, 0)
Emitting 2715 points for grid cell (0, 5, 0)
Emitting 5692 points for grid cell (1, 4, 0)
Emitting 4032 points for grid cell (1, 5, 0)
Emitting 2805 points for grid cell (0, 6, 0)
Emitting 723 points for grid cell (0, 7, 0)
Emitting 4085 points for grid cell (1, 6, 0)
Emitting 2277 points for grid cell (1, 7, 0)
Emitting 8882 points for grid cell (2, 4, 0)
Emitting 10000 points for grid cell (2, 5, 0)
Emitting 10000 points for grid cell (3, 4, 0)
Emitting 10000 points for grid cell (3, 5, 0)
Emitting 10000 points for grid cell (2, 6, 0)
Emitting 10000 points for grid cell (2, 7, 0)
Emitting 10000 points for grid cell (3, 6, 0)
Emitting 10000 points for grid cell (3, 7, 0)
Emitting 10000 points for grid cell (4, 0, 0)
Emitting 10000 points for grid cell (4, 1, 0)
Emitting 10000 points for grid cell (5, 0, 0)
Emitting 10000 points for grid cell (5, 1, 0)
Emitting 10000 points for grid cell (4, 2, 0)
Emitting 10000 points for grid cell (4, 3, 0)
Emitting 10000 points for grid cell (5, 2, 0)
Emitting 10000 points for grid cell (5, 3, 0)
Emitting 10000 points for grid cell (6, 0, 0)
Emitting 10000 points for grid cell (6, 1, 0)
Emitting 8428 points for grid cell (7, 0, 0)
Emitting 7898 points for grid cell (7, 1, 0)
Emitting 10000 points for grid cell (6, 2, 0)
Emitting 10000 points for grid cell (6, 3, 0)
Emitting 3193 points for grid cell (7, 2, 0)
Emitting 10000 points for grid cell (7, 3, 0)
Emitting 10000 points for grid cell (4, 4, 0)
Emitting 10000 points for grid cell (4, 5, 0)
Emitting 10000 points for grid cell (5, 4, 0)
Emitting 10000 points for grid cell (5, 5, 0)
Emitting 10000 points for grid cell (4, 6, 0)
Emitting 10000 points for grid cell (4, 7, 0)
Emitting 10000 points for grid cell (5, 6, 0)
Emitting 10000 points for grid cell (5, 7, 0)
Emitting 10000 points for grid cell (6, 4, 0)
Emitting 10000 points for grid cell (6, 5, 0)
Emitting 3694 points for grid cell (7, 4, 0)
Emitting 8278 points for grid cell (7, 5, 0)
Emitting 10000 points for grid cell (6, 6, 0)
Emitting 10000 points for grid cell (6, 7, 0)
Emitting 5354 points for grid cell (7, 6, 0)
Emitting 4778 points for grid cell (7, 7, 0)
Processing grid level 4 with shape (16, 16, 1) and chunk size [350500.        586937.5       110145.5234375]. Remaining points: 151712
Emitting 473 points for grid cell (6, 2, 0)
Emitting 261 points for grid cell (6, 3, 0)
Emitting 520 points for grid cell (7, 2, 0)
Emitting 488 points for grid cell (7, 3, 0)
Emitting 342 points for grid cell (6, 4, 0)
Emitting 495 points for grid cell (6, 5, 0)
Emitting 667 points for grid cell (7, 4, 0)
Emitting 757 points for grid cell (7, 5, 0)
Emitting 1121 points for grid cell (6, 6, 0)
Emitting 910 points for grid cell (6, 7, 0)
Emitting 1175 points for grid cell (7, 6, 0)
Emitting 347 points for grid cell (7, 7, 0)
Emitting 223 points for grid cell (4, 10, 0)
Emitting 318 points for grid cell (4, 11, 0)
Emitting 313 points for grid cell (5, 10, 0)
Emitting 638 points for grid cell (5, 11, 0)
Emitting 689 points for grid cell (6, 8, 0)
Emitting 1158 points for grid cell (6, 9, 0)
Emitting 948 points for grid cell (7, 8, 0)
Emitting 1053 points for grid cell (7, 9, 0)
Emitting 1479 points for grid cell (6, 10, 0)
Emitting 1674 points for grid cell (6, 11, 0)
Emitting 2294 points for grid cell (7, 10, 0)
Emitting 1945 points for grid cell (7, 11, 0)
Emitting 392 points for grid cell (4, 12, 0)
Emitting 393 points for grid cell (4, 13, 0)
Emitting 409 points for grid cell (5, 12, 0)
Emitting 522 points for grid cell (5, 13, 0)
Emitting 62 points for grid cell (4, 14, 0)
Emitting 33 points for grid cell (4, 15, 0)
Emitting 126 points for grid cell (5, 14, 0)
Emitting 31 points for grid cell (5, 15, 0)
Emitting 637 points for grid cell (6, 12, 0)
Emitting 1634 points for grid cell (6, 13, 0)
Emitting 1230 points for grid cell (7, 12, 0)
Emitting 1655 points for grid cell (7, 13, 0)
Emitting 1423 points for grid cell (6, 14, 0)
Emitting 866 points for grid cell (6, 15, 0)
Emitting 1254 points for grid cell (7, 14, 0)
Emitting 1156 points for grid cell (7, 15, 0)
Emitting 1417 points for grid cell (8, 0, 0)
Emitting 1734 points for grid cell (8, 1, 0)
Emitting 1255 points for grid cell (9, 0, 0)
Emitting 1786 points for grid cell (9, 1, 0)
Emitting 2193 points for grid cell (8, 2, 0)
Emitting 1303 points for grid cell (8, 3, 0)
Emitting 972 points for grid cell (9, 2, 0)
Emitting 782 points for grid cell (9, 3, 0)
Emitting 1444 points for grid cell (10, 0, 0)
Emitting 1893 points for grid cell (10, 1, 0)
Emitting 684 points for grid cell (11, 0, 0)
Emitting 831 points for grid cell (11, 1, 0)
Emitting 1270 points for grid cell (10, 2, 0)
Emitting 1885 points for grid cell (10, 3, 0)
Emitting 388 points for grid cell (11, 2, 0)
Emitting 646 points for grid cell (11, 3, 0)
Emitting 1761 points for grid cell (8, 4, 0)
Emitting 1934 points for grid cell (8, 5, 0)
Emitting 775 points for grid cell (9, 4, 0)
Emitting 721 points for grid cell (9, 5, 0)
Emitting 2264 points for grid cell (8, 6, 0)
Emitting 1345 points for grid cell (8, 7, 0)
Emitting 1581 points for grid cell (9, 6, 0)
Emitting 2027 points for grid cell (9, 7, 0)
Emitting 1223 points for grid cell (10, 4, 0)
Emitting 1637 points for grid cell (10, 5, 0)
Emitting 29 points for grid cell (11, 4, 0)
Emitting 31 points for grid cell (11, 5, 0)
Emitting 1614 points for grid cell (10, 6, 0)
Emitting 2398 points for grid cell (10, 7, 0)
Emitting 895 points for grid cell (11, 6, 0)
Emitting 1679 points for grid cell (11, 7, 0)
Emitting 1097 points for grid cell (12, 0, 0)
Emitting 1385 points for grid cell (12, 1, 0)
Emitting 705 points for grid cell (12, 2, 0)
Emitting 671 points for grid cell (12, 3, 0)
Emitting 54 points for grid cell (12, 4, 0)
Emitting 39 points for grid cell (12, 5, 0)
Emitting 1249 points for grid cell (12, 6, 0)
Emitting 2026 points for grid cell (12, 7, 0)
Emitting 284 points for grid cell (13, 6, 0)
Emitting 384 points for grid cell (13, 7, 0)
Emitting 175 points for grid cell (14, 6, 0)
Emitting 289 points for grid cell (14, 7, 0)
Emitting 249 points for grid cell (15, 6, 0)
Emitting 1487 points for grid cell (8, 8, 0)
Emitting 2533 points for grid cell (8, 9, 0)
Emitting 1397 points for grid cell (9, 8, 0)
Emitting 1682 points for grid cell (9, 9, 0)
Emitting 3124 points for grid cell (8, 10, 0)
Emitting 2649 points for grid cell (8, 11, 0)
Emitting 1953 points for grid cell (9, 10, 0)
Emitting 2072 points for grid cell (9, 11, 0)
Emitting 2569 points for grid cell (10, 8, 0)
Emitting 1949 points for grid cell (10, 9, 0)
Emitting 1328 points for grid cell (11, 8, 0)
Emitting 1113 points for grid cell (11, 9, 0)
Emitting 1125 points for grid cell (10, 10, 0)
Emitting 1954 points for grid cell (10, 11, 0)
Emitting 1051 points for grid cell (11, 10, 0)
Emitting 1348 points for grid cell (11, 11, 0)
Emitting 3039 points for grid cell (8, 12, 0)
Emitting 2424 points for grid cell (8, 13, 0)
Emitting 2068 points for grid cell (9, 12, 0)
Emitting 1458 points for grid cell (9, 13, 0)
Emitting 1504 points for grid cell (8, 14, 0)
Emitting 2489 points for grid cell (8, 15, 0)
Emitting 1331 points for grid cell (9, 14, 0)
Emitting 1505 points for grid cell (9, 15, 0)
Emitting 2699 points for grid cell (10, 12, 0)
Emitting 1866 points for grid cell (10, 13, 0)
Emitting 1136 points for grid cell (11, 12, 0)
Emitting 1052 points for grid cell (11, 13, 0)
Emitting 2107 points for grid cell (10, 14, 0)
Emitting 2087 points for grid cell (10, 15, 0)
Emitting 1598 points for grid cell (11, 14, 0)
Emitting 798 points for grid cell (11, 15, 0)
Emitting 1861 points for grid cell (12, 8, 0)
Emitting 901 points for grid cell (12, 9, 0)
Emitting 1186 points for grid cell (12, 10, 0)
Emitting 1260 points for grid cell (12, 11, 0)
Emitting 1627 points for grid cell (12, 12, 0)
Emitting 1610 points for grid cell (12, 13, 0)
Emitting 67 points for grid cell (12, 14, 0)
Emitting 1590 points for grid cell (12, 15, 0)
{
    "type": "neuroglancer_annotations_v1",
    "dimensions": {
        "x": [
            1.0,
            "nm"
        ],
        "y": [
            1.0,
            "nm"
        ],
        "z": [
            1.0,
            "nm"
        ]
    },
    "lower_bound": [
        112000.0,
        0.0,
        0.0
    ],
    "upper_bound": [
        5720000.0,
        9391000.0,
        110145.5234375
    ],
    "annotation_type": "POINT",
    "properties": [
        {
            "id": "gene",
            "type": "int16",
            "description": "",
            "enum_values": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                87,
                88,
                89,
                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                99,
                100,
                101,
                102,
                103,
                104,
                105,
                106,
                107,
                108,
                109,
                110,
                111,
                112,
                113,
                114,
                115,
                116,
                117,
                118,
                119,
                120,
                121,
                122,
                123,
                124,
                125,
                126,
                127,
                128,
                129,
                130,
                131,
                132,
                133,
                134,
                135,
                136,
                137,
                138,
                139,
                140,
                141,
                142,
                143,
                144,
                145,
                146,
                147,
                148,
                149,
                150,
                151,
                152,
                153,
                154,
                155,
                156,
                157,
                158,
                159,
                160,
                161,
                162,
                163,
                164,
                165,
                166,
                167,
                168,
                169,
                170,
                171,
                172,
                173,
                174,
                175,
                176,
                177,
                178,
                179,
                180,
                181,
                182,
                183,
                184,
                185,
                186,
                187,
                188,
                189,
                190,
                191,
                192,
                193,
                194,
                195,
                196,
                197,
                198,
                199,
                200,
                201,
                202,
                203,
                204,
                205,
                206,
                207,
                208,
                209,
                210,
                211,
                212,
                213,
                214,
                215,
                216,
                217,
                218,
                219,
                220,
                221,
                222,
                223,
                224,
                225,
                226,
                227,
                228,
                229,
                230,
                231,
                232,
                233,
                234,
                235,
                236,
                237,
                238,
                239,
                240
            ],
            "enum_labels": [
                "Acsl1",
                "Acta2",
                "Ada",
                "Adgrd1",
                "Adgrf5",
                "Adra1a",
                "Adra1b",
                "Adra1d",
                "Adra2a",
                "Adra2b",
                "Adra2c",
                "Adrb1",
                "Adrb2",
                "Adrb3",
                "Agr3",
                "Apob",
                "Avil",
                "C1qb",
                "C1qc",
                "Cadm1",
                "Cckar",
                "Cckbr",
                "Ccl9",
                "Ccnl2",
                "Ccr3",
                "Ccr7",
                "Cd14",
                "Cd27",
                "Cd34",
                "Cd3d",
                "Cd3e",
                "Cd4",
                "Cd44",
                "Cd79a",
                "Cd79b",
                "Cd8a",
                "Cd8b1",
                "Chrm1",
                "Chrm2",
                "Chrm3",
                "Chrm4",
                "Chrm5",
                "Clca3b",
                "Clec4a2",
                "Clec9a",
                "Cmc1",
                "Cnr1",
                "Cps1",
                "Crp",
                "Cspg4",
                "Cxcr5",
                "Cysltr1",
                "Cysltr2",
                "Drd1",
                "Drd2",
                "Drd3",
                "Drd4",
                "Drd5",
                "Elavl3",
                "Etv1",
                "Fcer1a",
                "Fcgr4",
                "Fcna",
                "Ffar1",
                "Ffar2",
                "Ffar3",
                "Ffar4",
                "Foxp3",
                "Fzd1",
                "Fzd10",
                "Fzd2",
                "Fzd3",
                "Fzd4",
                "Fzd5",
                "Fzd6",
                "Fzd7",
                "Fzd8",
                "Fzd9",
                "Galr1",
                "Galr2",
                "Galr3",
                "Gcgr",
                "Ghsr",
                "Gipr",
                "Glp1r",
                "Glp2r",
                "Gp2",
                "Gpbar1",
                "Gper1",
                "Gpr119",
                "Gpr174",
                "Gpr18",
                "Gpr31b",
                "Gpr34",
                "Gpr55",
                "Gpr84",
                "Gpr87",
                "Gzmb",
                "H2-Eb1",
                "Hhex",
                "Hmgb2",
                "Hrh1",
                "Hrh2",
                "Hrh3",
                "Hrh4",
                "Htr1a",
                "Htr1b",
                "Htr1d",
                "Htr1f",
                "Htr2a",
                "Htr2b",
                "Htr2c",
                "Htr4",
                "Htr5a",
                "Htr5b",
                "Htr6",
                "Htr7",
                "Icos",
                "Ifnar1",
                "Ifng",
                "Ighd",
                "Il10",
                "Il17a",
                "Il3ra",
                "Il4",
                "Il5",
                "Il7r",
                "Il9",
                "Isl1",
                "Itgae",
                "Itgam",
                "Jaml",
                "Kiss1r",
                "Kit",
                "Klk1",
                "Krt7",
                "Lamp3",
                "Lct",
                "Lgr5",
                "Lmx1a",
                "Lpar1",
                "Lpar2",
                "Lpar3",
                "Lpar4",
                "Lpar5",
                "Lpar6",
                "Lrmp",
                "Ltb4r1",
                "Ltb4r2",
                "Ly6g",
                "Maged2",
                "Maoa",
                "Marcksl1",
                "Mboat4",
                "Mki67",
                "Mpo",
                "Mptx2",
                "Ms4a1",
                "Mzb1",
                "Neat1",
                "Nes",
                "Net1",
                "Neurog3",
                "Nkg7",
                "Nlrp6",
                "Nt5e",
                "Ntsr1",
                "Ntsr2",
                "P2ry10",
                "P2ry10b",
                "Pax6",
                "Phox2b",
                "Plb1",
                "Prf1",
                "Ptgdr",
                "Ptgdr2",
                "Ptger1",
                "Ptger2",
                "Ptger3",
                "Ptger4",

In [14]:
print('done')

done

We have APIs to load the data from disk back to memory. Note the last columns `__spatial_index__` and `__chunk_key__`. These would enable compatibility with tools like [celldega](https://github.com/broadinstitute/celldega).

In [17]:
df_annotations = parse_annotations(Path(precomputed_path))
df_annotations

,x,y,z,gene,area,mol_id,x_raw,y_raw,z_raw,brightness,total_magnitude,compartment,nuclei_probs,assignment_confidence,cell,is_noise,layer,__spatial_index__,__chunk_key__
651794,2954000.0,2811000.0,96377.335938,Cps1,4,16702081,-2799.281006,-1050.797974,13.0,2.036481,435.052185,Unknown,0.964550,0.975,1108,0,8,spatial0,0_0_0
109770,3752000.0,6752000.0,27536.380859,Sdc1,5,3446830,-2712.323975,-621.414124,5.5,1.901822,398.834198,Cyto,0.009514,0.725,3338,0,3,spatial0,0_0_0
411491,4505000.0,976000.0,68840.953125,Maoa,7,9985399,-2630.342041,-1250.633057,10.0,1.758948,401.833313,Unknown,1.000000,0.575,890,0,6,spatial0,0_0_0
802835,4064000.0,7449000.0,13768.190430,Nlrp6,5,17113867,-2678.417969,-545.486389,4.0,1.770261,294.598602,Cyto,0.008998,1.000,3723,0,2,spatial0,0_0_0
396099,3558000.0,40000.0,0.000000,Clca3b,7,9877582,-2733.547119,-1352.660034,2.5,2.101502,884.300415,Unknown,0.997284,1.000,198,0,1,spatial0,0_0_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367369,3337000.0,5082000.0,41304.574219,Slc5a1,8,9770339,-2757.532959,-803.313721,7.0,1.575751,301.190186,Cyto,0.010725,0.550,2258,0,4,spatial4,8_8_0
363023,3228000.0,4836000.0,68840.953125,Neat1,7,9763927,-2769.425049,-830.134521,10.0,1.969285,652.203186,Unknown,1.000000,0.525,2105,0,6,spatial4,8_8_0
356640,3156000.0,4997000.0,55072.761719,Net1,8,9754339,-2777.291992,-812.597412,8.5,1.870503,593.734924,Cyto,0.010267,1.000,2150,0,5,spatial4,8_8_0
349917,3106000.0,5121000.0,96377.335938,Slc12a2,4,9735836,-2782.708984,-799.095276,13.0,1.764960,232.820007,Unknown,0.875873,1.000,2230,0,8,spatial4,8_8_0
327228,3115000.0,4983000.0,55072.761719,Cps1,13,9701772,-2781.782959,-814.130127,8.5,1.930329,1107.318970,Nuclei,0.935640,1.000,2150,0,5,spatial4,8_8_0